#
# THIS IS AN EXAMPLE FILE WORKING WITH TRAEFIK ONLY
#
# Copy .env.dist to .env to customize your domain names.
#
version: '3'
services:
  web:
    image: 'gitlab/gitlab-ce:latest'
    restart: always
    #
    # Alias is needed for Mattermost
    # to be able to contact Gitlab SSO
    #
    hostname: ${HOSTNAME}
    # Using Traefik
    # https://docs.traefik.io/user-guide/docker-and-lets-encrypt/
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.gitlab.rule=Host(`${HOSTNAME}`)"
      - "traefik.http.routers.gitlab.entrypoints=http,https"
      - "traefik.http.services.gitlab.loadbalancer.server.port=80"

      - "traefik.http.routers.registry.rule=Host(`${REGISTRY_HOSTNAME}`)"
      - "traefik.http.routers.registry.entrypoints=http,https"
      - "traefik.http.services.registry.loadbalancer.server.port=80"

      - "traefik.http.routers.mattermost.rule=Host(`${MATTERMOST_HOSTNAME}`)"
      - "traefik.http.routers.mattermost.entrypoints=http,https"
      - "traefik.http.services.mattermost.loadbalancer.server.port=3000"
    # I had problems with the health check. Sometimes it reported unhealthyness and therefore Traefik removed
    # the container, so I turned it off. Maybe it works by now.
    healthcheck:
      disable: true
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'https://${HOSTNAME}'
        nginx['redirect_http_to_https'] = false
        nginx['listen_port'] = 80
        nginx['listen_https'] = false
        nginx['proxy_set_headers'] = {
          'X-Forwarded-Proto' => 'https',
          'X-Forwarded-Ssl' => 'on'
        }
        nginx['client_max_body_size'] = '2G'
        gitlab_rails['smtp_enable'] = true
        gitlab_rails['smtp_address'] = "${SMTP_ADDRESS}"
        gitlab_rails['smtp_port'] = ${SMTP_PORT}
        gitlab_rails['smtp_user_name'] = "${SMTP_USERNAME}"
        gitlab_rails['smtp_password'] = "${SMTP_PASSWORD}"
        gitlab_rails['smtp_domain'] = "${SMTP_DOMAIN}"
        gitlab_rails['smtp_authentication'] = "login"
        gitlab_rails['smtp_enable_starttls_auto'] = true
        gitlab_rails['gitlab_email_from'] = 'gitlab-notifications@${SMTP_DOMAIN}'
        gitlab_rails['gitlab_email_display_name'] = 'Gitlab'
        gitlab_rails['gitlab_email_reply_to'] = 'noreply@${SMTP_DOMAIN}'
        unicorn['worker_timeout'] = 60
        unicorn['worker_processes'] = 2
        sidekiq['concurrency'] = 15
        postgresql['shared_buffers'] = "512MB"
        gitlab_rails['artifacts_enabled'] = true
        gitlab_rails['artifacts_path'] = "/var/opt/gitlab/gitlab-artifacts"
        gitlab_rails['lfs_enabled'] = true
        gitlab_rails['backup_keep_time'] = 172600
        gitlab_ci['backup_keep_time'] = 172600
        gitlab_rails['time_zone'] = "${TIMEZONE}"

        #
        # Docker registry
        #
        registry_external_url 'https://${REGISTRY_HOSTNAME}'
        gitlab_rails['registry_enabled'] = true
        registry_nginx['listen_port'] = 80
        registry_nginx['listen_https'] = false

        #
        # First run this stack before
        # configuring Mattermost
        #
        mattermost_external_url 'https://${MATTERMOST_HOSTNAME}'
        mattermost['enable'] = true
        mattermost['service_site_url'] = 'https://${MATTERMOST_HOSTNAME}'
        mattermost_nginx['listen_port'] = 3000
        mattermost_nginx['listen_https'] = false
        mattermost_nginx['redirect_http_to_https'] = false
        mattermost_nginx['proxy_set_headers'] = {
          "X-Forwarded-Proto" => "https",
          "X-Forwarded-Ssl" => "on",
        }
        mattermost['service_use_ssl'] = false
        mattermost['gitlab_id'] = "${MATTERMOST_GITLAB_ID}"
        mattermost['gitlab_secret'] = "${MATTERMOST_GITLAB_SECRET}"
        mattermost['gitlab_scope'] = ""
        #
        # Need to contact Gitlab on HTTP
        # https://forum.mattermost.org/t/solved-mattermost-gitlab-token-request-failed/2628/6
        #
        mattermost['gitlab_auth_endpoint'] = "http://${HOSTNAME}/oauth/authorize"
        mattermost['gitlab_token_endpoint'] = "http://${HOSTNAME}/oauth/token"
        mattermost['gitlab_user_api_endpoint'] = "http://${HOSTNAME}/api/v4/user"

    ports:
      # Make sure your host 22 port is not already taken by SSH
      # We encorage you to change you host SSH port to reserve it for Gitlab
      - '22:22'
    volumes:
      - config:/etc/gitlab
      - logs:/var/log/gitlab
      - data:/var/opt/gitlab
      - ./../traefik/ssl:/etc/gitlab/ssl/:ro

networks:
  default:
    external:
      name: frontproxynet

volumes:
  config:
  logs:
  data:
